version: '3.4'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse
    restart: unless-stopped
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    build:
      context: ./node-red
    privileged: true
    ports:
      - "1880:1880"
    networks:
      - reverse
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`node-red`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=1880"
    networks:
      - reverse
    user: root
    restart: unless-stopped
    volumes:
      - ./node-red-data:/data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - reverse
  elasticsearch:
    platform: "linux/${ARCH:-amd64}"
    image: elasticsearch:8.3.2
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
volumes:
   esdata1:
    driver: local
networks:
  reverse:
    driver: bridge
