version: '3.4'

services:
  plex:
    image: ghcr.io/linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/main/Movies:/movies
    restart: unless-stopped
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variable
      - USER=bartlomiejmarszal@gmail.com     # Required
      - "PASS=suqta3-kYvvaw-sawzus"         # Required
      - CONNECT=Belgium
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24 
    ports:
      - 8080:8080

  torrent:
    image: linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn
volumes:
  timemachine-var-lib-samba:
    driver: local
  timemachine-run-samba:
    driver: local
  timemachine-var-cache-samba:
    driver: local
