version: '3.4'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - reverse
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`node-red`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=1880"
    networks:
      - reverse
    user: root
    volumes:
      - node-red-data:/data
volumes:
  portainer_data:
  node-red-data:
networks:
  reverse:
    driver: bridge
